# Generated by Django 4.1.1 on 2022-09-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='permanentbooking',
            constraint=models.UniqueConstraint(fields=('student', 'lesson'), name='unique_student_lesson'),
        ),
    ]
