# Generated by Django 4.1.1 on 2022-09-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_permanentbooking_unique_student_lesson'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('student', 'lesson', 'date'), name='unique_student_lesson_date'),
        ),
    ]
