# Generated by Django 4.1.1 on 2022-09-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_unique_student_lesson_date'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.CheckConstraint(check=models.Q(('date_begin__lt', models.F('date_end'))), name='check_dates'),
        ),
    ]
