# Generated by Django 4.1.1 on 2022-09-14 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_schedule_check_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.schedule', verbose_name='Занятие'),
        ),
        migrations.AlterField(
            model_name='permanentbooking',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_bookings', to='booking.schedule', verbose_name='Занятие'),
        ),
    ]
