# Generated by Django 4.1.1 on 2022-09-14 22:59

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_lesson_alter_permanentbooking_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='week_days',
            field=models.CharField(max_length=7, validators=[booking.models.validate_schedule_week_days], verbose_name='Дни проведения занятий'),
        ),
    ]
