# Generated by Django 4.1.1 on 2022-09-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_schedule_week_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='bootstrap_icon',
            field=models.CharField(default='', max_length=50, verbose_name='Иконка'),
        ),
    ]
