# Generated by Django 4.1.1 on 2022-09-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_lesson_bootstrap_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Решение идти на занятие'),
        ),
    ]
