# Generated by Django 4.1.1 on 2022-09-19 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_booking_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PermanentBooking',
        ),
    ]
