# Generated by Django 4.1.1 on 2022-09-19 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_delete_permanentbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
    ]
