# Generated by Django 4.1.1 on 2022-09-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='bootstrap_icon',
            field=models.CharField(default='bi-emoji-smile', help_text='https://icons.getbootstrap.com/icons/', max_length=50, verbose_name='Иконка'),
        ),
    ]
