# Generated by Django 4.1.1 on 2022-09-19 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_alter_lesson_bootstrap_icon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
