# Generated by Django 4.1.1 on 2022-09-19 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('lesson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.lesson')),
                ('datetime_begin', models.DateTimeField(verbose_name='Время начала мероприятия')),
                ('datetime_end', models.DateTimeField(verbose_name='Время завершения мероприятия')),
                ('deadline_booking', models.DateTimeField(verbose_name='Время завершения бронирования')),
                ('price', models.PositiveIntegerField(verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ('-datetime_begin',),
            },
            bases=('booking.lesson',),
        ),
    ]
